// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwr_joMxeRGFN_kRZeDnk4sTpkJxKRuow',
    appId: '1:964586361849:web:91a04e0e7ee595853e2328',
    messagingSenderId: '964586361849',
    projectId: 'naivedhya-942d8',
    authDomain: 'naivedhya-942d8.firebaseapp.com',
    storageBucket: 'naivedhya-942d8.firebasestorage.app',
    measurementId: 'G-3QLK4WFKFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmEIGAqBvzhfxCe-LHY-1rz0zFxIMjaLo',
    appId: '1:964586361849:android:7dd1fd8e7f6beefe3e2328',
    messagingSenderId: '964586361849',
    projectId: 'naivedhya-942d8',
    storageBucket: 'naivedhya-942d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTuepaLZ8Eq4fSrUE5ss-hMbD__3089vs',
    appId: '1:964586361849:ios:ca1c9a7519601dba3e2328',
    messagingSenderId: '964586361849',
    projectId: 'naivedhya-942d8',
    storageBucket: 'naivedhya-942d8.firebasestorage.app',
    androidClientId: '964586361849-go88niipkaq037ovs7nakgf3ua86mg15.apps.googleusercontent.com',
    iosClientId: '964586361849-ub3hahrqusrl371curnm6a5hhrb6som3.apps.googleusercontent.com',
    iosBundleId: 'com.example.naivedhya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTuepaLZ8Eq4fSrUE5ss-hMbD__3089vs',
    appId: '1:964586361849:ios:ca1c9a7519601dba3e2328',
    messagingSenderId: '964586361849',
    projectId: 'naivedhya-942d8',
    storageBucket: 'naivedhya-942d8.firebasestorage.app',
    androidClientId: '964586361849-go88niipkaq037ovs7nakgf3ua86mg15.apps.googleusercontent.com',
    iosClientId: '964586361849-ub3hahrqusrl371curnm6a5hhrb6som3.apps.googleusercontent.com',
    iosBundleId: 'com.example.naivedhya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwr_joMxeRGFN_kRZeDnk4sTpkJxKRuow',
    appId: '1:964586361849:web:37d340ed0193e6983e2328',
    messagingSenderId: '964586361849',
    projectId: 'naivedhya-942d8',
    authDomain: 'naivedhya-942d8.firebaseapp.com',
    storageBucket: 'naivedhya-942d8.firebasestorage.app',
    measurementId: 'G-S41KXYWXNR',
  );
}
